# Generated by Django 4.1.7 on 2023-03-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='student_loan_interest',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
