# Generated by Django 4.1 on 2023-02-22 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charitable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributions', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled', models.BooleanField()),
                ('college_expenses', models.FloatField(blank=True, null=True)),
                ('scholarships_received', models.FloatField(blank=True, null=True)),
                ('demographics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalApp.demographics')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own', models.BooleanField()),
                ('interest_taxes', models.FloatField(blank=True, null=True)),
                ('demographics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalApp.demographics')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_income', models.FloatField()),
                ('demographics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalApp.demographics')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses', models.FloatField()),
                ('demographics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalApp.demographics')),
            ],
        ),
        migrations.CreateModel(
            name='Retirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributions', models.FloatField()),
                ('demographics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalApp.demographics')),
            ],
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_tax', models.FloatField()),
                ('demographics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalApp.demographics')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxes_registration', models.FloatField()),
                ('demographics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalApp.demographics')),
            ],
        ),
        migrations.DeleteModel(
            name='TaxCalculation',
        ),
        migrations.AddField(
            model_name='charitable',
            name='demographics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalApp.demographics'),
        ),
    ]
