# Generated by Django 4.1 on 2023-02-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalApp', '0002_charitable_demographics_education_home_income_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_income', models.FloatField()),
                ('federal_tax', models.FloatField()),
            ],
        ),
    ]
