# Generated by Django 4.1 on 2023-02-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalApp', '0003_taxcalculation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charitable',
            old_name='contributions',
            new_name='charitable_contributions',
        ),
        migrations.RenameField(
            model_name='medical',
            old_name='expenses',
            new_name='medical_expenses',
        ),
        migrations.RenameField(
            model_name='retirement',
            old_name='contributions',
            new_name='retirement_contributions',
        ),
    ]
